# ergomcu tool configuration

general:
  arm_toolchain_path: /usr/bin
  openocd_path:  /usr/bin/openocd
  openocd_script_path: /usr/share/openocd/scripts

# Define the location of external libraries that are used in your STM32 projects
libraries:
  - var: ERGOMCU_LIB_PATH
    path:     ~/ergomcu


openocd:
  # Define the hardware you use to write data into the MCUs and to debug.
  # The extensive list of supported devices is usually located
  # at /usr/share/openocd/scripts/interface/
  interface: stlink.cfg
