# ergomcu tool configuration
# This file contains machine-specific information
# that normally shouldn't be committed, e.g. local library paths,
# your hardware description etc.

general:
  # Path to your ARM C compiler (usually arm-none-eabi-gcc)
  arm_toolchain_path: /usr/bin

openocd:
  # Define the hardware you use to write data and debug the MCU.
  # The extensive list of supported devices is usually located
  # at /usr/share/openocd/scripts/interface/ in Ubuntu.
  interface: stlink.cfg
  # Path to openocd executable
  bin_path:  /usr/bin/openocd
  # Path to the openocd scripts directory
  scripts_path: /usr/share/openocd/scripts


# External dependencies are libraries
# or directories with source files that you may use in your projects.
# This setting is the same as in the 'ergomcu_project.yaml' file,
# but these values have precedence in case of a conflict.
# Note that it is recommended to only specify machine-dependent paths
# that you are NOT going to commit to the repository here.
# Machine-independent paths should be specified as a part of your project
# in the 'ergomcu_project.yaml'.
external_dependencies:
#  - var:                     EXAMPLE_LIB
#    path:                    /path/to/example/lib
#    create_in_project_link:  true
#    link_name:               example_lib
