# This is a configuration file for ergomcutool v1.0.0.
# It contains machine-specific settings that are not committed
# e.g. local paths, your hardware description etc.

general:
  # Path to your ARM C compiler (usually arm-none-eabi-gcc) directory
  arm_toolchain_path: /usr/bin
  # Full path to your ARM C compiler
  c_compiler_path: /usr/bin/arm-none-eabi-gcc
  # Full path to your ARM C++ compiler
  cpp_compiler_path: /usr/bin/arm-none-eabi-g++
  # Full path to your ARM debugger
  debugger_path: /usr/bin/gdb-multiarch

openocd:
  # Define the hardware you use to write data and debug the MCU.
  # The extensive list of supported devices is usually located
  # at /usr/share/openocd/scripts/interface/ in Ubuntu.
  interface: stlink.cfg
  # Path to openocd executable
  bin_path:  /usr/bin/openocd
  # Path to the openocd scripts directory
  scripts_path: /usr/share/openocd/scripts
  # Path to the .svd file for your specific MCU device.
  # If the .svd file is included as a part of your project,
  # you should specify it in 'ergomcutool/ergomcu_project.yaml' instead.
  svd_file_path:
  # If you don't use the .svd file in your project,
  # you might want to disable the warning.
  disable_svd_warning: false

# External dependencies are libraries
# or directories with source files that you may use in your projects.
# This setting is the same as in the 'ergomcu_project.yaml' file,
# but these values have precedence in case of a conflict.
# Note that it is recommended to only specify here machine-dependent paths
# that you are NOT going to commit to the repository.
# Machine-independent paths should be specified as a part of your project
# in the 'ergomcu_project.yaml'.
external_dependencies:
#  - var:                     EXAMPLE_LIB
#    path:                    /path/to/example/lib
#    create_in_project_link:  true
#    link_name:               example_lib


# Build options are supposed to be specified in local ergomcutool_config.yaml files.
# If not specified, the default values generated by CubeMX will be used.
build_options:
#  build_dir: build
#  debug:     1
#  optimization_flags: -Og
