package iocfile

import (
	"strings"

	"github.com/mcu-art/ergomcutool/utils"
)

// IocFileData contains some fields of interest from the .ioc file
// generated by CubeMX.
type IocFileData struct {
	ProjectName        string
	DeviceId           string
	UAScriptAfterPath  string // ProjectManager.UAScriptAfterPath
	UAScriptBeforePath string // ProjectManager.UAScriptBeforePath
}

func ParseIocFile(path string) (*IocFileData, error) {
	lines, err := utils.ReadTextFile(path)
	if err != nil {
		return nil, err
	}
	result := &IocFileData{}
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "ProjectManager.ProjectName") {
			substrings := strings.Split(line, "=")
			if len(substrings) > 1 {
				result.ProjectName = substrings[1]
			}
		}
		if strings.HasPrefix(line, "ProjectManager.DeviceId") {
			substrings := strings.Split(line, "=")
			if len(substrings) > 1 {
				result.DeviceId = substrings[1]
			}
		}
		if strings.HasPrefix(line, "ProjectManager.UAScriptAfterPath") {
			substrings := strings.Split(line, "=")
			if len(substrings) > 1 {
				result.UAScriptAfterPath = substrings[1]
			}
		}
		if strings.HasPrefix(line, "ProjectManager.UAScriptBeforePath") {
			substrings := strings.Split(line, "=")
			if len(substrings) > 1 {
				result.UAScriptBeforePath = substrings[1]
			}
		}
	}
	return result, nil
}
